### ISSUE TITLE
import Streamly playlists

### ISSUE THREAD

**Issue by select** [select/audius#36]
Import playlist files from Streamly https://github.com/LNFWebsite/Streamly

@LNFWebsite how do you store playlists? Can you post a JSON example?

**Comment by LNFWebsite** [comment]
Streamly playlists are stored as [`Base64`](https://en.wikipedia.org/wiki/Base64) encoded two-dimensional arrays containing the video's name, time, and video_id.

Playlist names and video names are URIComponent encoded to prevent encoding anomalies, then replaced of the `%20`s which are URIEncoded spaces to normal spaces since this raises the normally 1 character of space to 3. All of this is done to squeeze the size of the playlist to the smallest possible length.

This encoding is done like so:

    videoName = encodeURIComponent(videoName).replace(/%20/g, " ");

As an example of a Streamly playlist:

https://lnfwebsite.github.io/Streamly/#W251bGwsWyJKaW0gQ3JvY2UgLSBUaW1lIGluIGEgYm90dGxlIC0gMTk3MyIsMTQ5LCJkTzFyTWVZbk9tTSJdLFsiSmltIENyb2NlIC0gSSdsbCBIYXZlIFRvIFNheSBJIExvdmUgWW91IEluIEEgU29uZyAgKDE5NzMpIiwxNTAsIkVOMW5NcG1DMG40Il0sWyJKaW0gQ3JvY2UgLSBJIEdvdCBhIE5hbWUgKDE5NzMpIiwxODksIlljcWF1QzQ5WG1jIl0sWyJEb24gTWNMZWFuIC0gVmluY2VudCAoIFN0YXJyeSUyQyBTdGFycnkgTmlnaHQpIFdpdGggTHlyaWNzIiwyMzksIm94SG5SZmhEbXJrIl1d

The Base64 code converts to:

    [null, ["Jim Croce - Time in a bottle - 1973", 149, "dO1rMeYnOmM"],
    	["Jim Croce - I'll Have To Say I Love You In A Song  (1973)", 150, "EN1nMpmC0n4"],
    	["Jim Croce - I Got a Name (1973)", 189, "YcqauC49Xmc"],
    	["Don McLean - Vincent ( Starry%2C Starry Night) With Lyrics", 239, "oxHnRfhDmrk"]
    ]

`null` is the playlist name. When empty it is set as `null` as a placeholder. When filled, it is just a string: `"Jim Croce Mix"` Likewise, URIEncoded for funky characters.

To build a playlist you could use a function like so...

    var playlistName = "name of playlist"
    
    var videoName = "name of video";
    var videoTime = "(length of video in seconds)"
    var videoId = "gxEPV4kolz0";
    
    if (playlistName !== "") {
      playlistName = encodeURIComponent(playlistName).replace(/%20/g, " ");
    }
    else {
      playlistName = null;
    }

    videoName = encodeURIComponent(videoName).replace(/%20/g, " ");
    
    var playlist = [];
    
    playlist.push(playlistName);
    
    var video = [];
    video[0] = videoName;
    video[1] = videoTime;
    video[2] = videoId;

    playlist.push(video);

_Note: I didn't test the code above, but it looks like it should work fine._
